matrix:
  fast_finish: true
  
  include:
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - TEST="Clang 5 without tests"
      script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_CXX_COMPILER="clang++-5.0" ..
        - make
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - TEST="GCC 7 with tests"
      script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_CXX_COMPILER="g++-7" -Dtest=ON ..
        - make
        - ctest -V
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - TEST="Clang 5 with tests"
      script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_CXX_COMPILER="clang++-5.0" -Dtest=ON ..
        - make
        - ctest -V

language: cpp

notifications:
  email: false