language: cpp

compiler: clang

install:
  - sudo apt-get install libgtest libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake
  - sudo make
  - sudo make install

script:
  - cmake -G "Unix Makefiles" -Dtest=ON
  - make
  - ctest