matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - TEST="Clang 5 without tests"
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
      script:
        - mkdir build
        - cd build
        - cmake ..
        - make
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - TEST="GCC 7 with tests"
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      script:
        - mkdir build
        - cd build
        - cmake -Dtest=ON ..
        - make
        - ctest -V
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - TEST="Clang 5 with tests"
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
      script:
        - mkdir build
        - cd build
        - cmake -Dtest=ON ..
        - make
        - ctest -V

language: cpp

before_install:
  - eval "${MATRIX_EVAL}"

notifications:
  email: false