image: Visual Studio 2017

platform:
  - x64

configuration:
  - Debug

environment:
  matrix:
    - project_name: ALL_BUILD.vcxproj
      test: -Dtest=OFF
    - project_name: RUN_TESTS.vcxproj
      test: -Dtest=ON

before_build:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 15 2017 Win64" %test% ..

build_script:
  - msbuild %project_name%
