image: Visual Studio 2017

platform:
  - x64

configuration:
  - Release
  - Debug

matrix:
  - env:
      - TEST="VS 2017 without tests"
    before_build:
      - mkdir build
      - cd build
      - cmake -G "Visual Studio 15 2017 Win64" .
  - env:
      - TEST="VS 2017 with tests"
    before_build:
      - mkdir build
      - cd build
      - cmake -G "Visual Studio 15 2017 Win64" .

build:
  project: ALL_BUILD.sln

language: cpp

notifications:
  email: false