image: Visual Studio 2017

platform:
  - x64

configuration:
  - Release
  - Debug

before_build:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 15 2017 Win64" -Dtest=ON ..

build:
  project: ALL_BUILD.sln
